### ISSUE TITLE
Akwel - the jobs from Scrapers-UI does not correspond with the jobs from the official website

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/Scrapers_Cristi_Olteanu#74]
ENVIROMENT: production
COMPANY: Akwel
URL: [Akwel peviitor.ro](https://scrapers.peviitor.ro/src/superbet/)
Company's Career website: [Akwel official website](https://boards.eu.greenhouse.io/superbet)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
1. Enter Akwel in the search bar.
2. Click the button below the company logo.
3. Click the button Run Scraper.

Expected results:
The number of jobs on [Scrapers-UI](https://scrapers.peviitor.ro/src/akwel/) corresponds to the number of jobs on [Akwel](https://akwel-automotive.com/en/careers/job-opportunities/) official website

Actual result:
The number of jobs on [Scrapers-UI](https://scrapers.peviitor.ro/src/akwel/) does not correspond to the number of jobs on [Akwel](https://akwel-automotive.com/en/careers/job-opportunities/) official website

<img width="1481" alt="Screenshot at Dec 13 13-49-19" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/d2b7d45a-987e-417d-b23e-f8aa1494b9b1">

<img width="423" alt="Screenshot at Dec 13 13-45-02" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/be48261c-1f8f-4ebd-aaa4-de9cc171d2bb">

**Comment by cristiol** [comment]
The website currently has a bug when it comes to filtering because it displays 10 jobs, but in reality, there are 12 jobs (11 jobs written as 'Roumania' and one as 'Romania' totaling exactly 12, as brought by the scraper)

![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/18a4d4e9-c457-40c0-a1fd-40d2527eb18f)
![image](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/142798921/e2988c23-52c3-44f0-b7a3-d754a35fff5b)
